# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Guess or Pass' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Guess or Pass

  target 'Guess or PassTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Guess or PassUITests' do
    # Pods for testing
  end

end
